config/routes.rb
MobSyncBackend::Application.routes.draw do
  resources :mobs
  resources :users

  root 'users#index'
  post 'login', to: 'users#login'

  post 'usersearch', to: 'users#search'
  post 'mymobs', to: 'mobs#mymobs'
  post 'confirm', to: 'mobs#confirm'
end

app/models/mob.rb
require 'apns'

class Mob < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  has_many :participants
  has_many :users, through: :participants

  validates_presence_of :user_id, :user_idz, :destination

  before_create :set_unix_timestamp
  after_create :create_participants, :send_push_notification

  def user
    User.find(self.user_id)
  end

  def set_unix_timestamp
    self.unix_timestamp = Time.now.strftime('%-m/%-d/%Y')
  end

  def create_participants
    self.user_idz.split(',').each do |user_id|
      Participant.create(mob_id: self.id, user_id: user_id, status: 0)
    end

    Participant.create(mob_id: self.id, user_id: self.user_id, status: 1)
  end

  def send_push_notification
    APNS.pem = 'app/assets/cert.pem'

    self.participants.each do |participant|
      params = {
        :alert => "You have #{pluralize participant.mob.participants.count-1, 'friend'} mobbing to #{participant.mob.destination}!",
        :other => {
          :mob_id => self.id
        }
      }

      APNS.send_notification(participant.user.device_id, params)
    end
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :user
  belongs_to :mob

  validates_presence_of :mob_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participants
  has_many :mobs, through: :participants

  validates_presence_of :username, :password, :name, :device_id
  validates_uniqueness_of :username

  before_create :format_device_id

  def format_device_id
    self.device_id = self.device_id.gsub('<','').gsub('>','').gsub(' ','')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mobs_controller.rb
class MobsController < ApplicationController
  before_action :set_mob, only: [:show, :edit, :update, :destroy]

  # GET /mobs
  # GET /mobs.json
  def index
    @mobs = Mob.all

    Mob.first.send_push_notification
  end

  # GET /mobs/1
  # GET /mobs/1.json
  def show
    respond_to do |format|
      people = @mob.user_idz.split(',').map{|i| User.find(i).name }.join(', ')
      format.json { render json: @mob.attributes.merge(people: people, users: @mob.users, date: Time.now.strftime('%-m/%-d/%Y')) }
    end
  end

  def mymobs
    user = User.find_by_username(params[:username])
    mobs = user.mobs

    if mobs.length > 0
      rendermobs = {}

      mobs.each do |mob|
        status = mob.participants.find_by_user_id(user).status
        rendermobs["mob#{mob.id}"] = {status: status}.merge(mob.attributes)
      end
      render json: rendermobs
    else
      render nothing: true
    end
  end

  def confirm
    user = User.find_by_username(params[:username])
    participant = Participant.where('mob_id = ? AND user_id = ?', params[:mob_id], user.id)

    participant.status = 1
    participant.save
  end

  # GET /mobs/new
  def new
    @mob = Mob.new
  end

  # GET /mobs/1/edit
  def edit
  end

  # POST /mobs
  # POST /mobs.json
  def create
    @mob = Mob.new
    @mob.user_id = User.where('username LIKE ?', mob_params[:username]).first.id
    @mob.user_idz = params[:usernames].split(',').map{|u| User.find_by_username(u).id }.join(',')
    @mob.destination = params[:destination]

    respond_to do |format|
      if @mob.save
        format.html { redirect_to @mob, notice: 'Mob was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mob }
      else
        format.html { render action: 'new' }
        format.json { render json: @mob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobs/1
  # PATCH/PUT /mobs/1.json
  def update
    respond_to do |format|
      if @mob.update(mob_params)
        format.html { redirect_to @mob, notice: 'Mob was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobs/1
  # DELETE /mobs/1.json
  def destroy
    @mob.destroy
    respond_to do |format|
      format.html { redirect_to mobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mob
      @mob = Mob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mob_params
      params.permit(:user_id, :user_idz, :destination, :username)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end


  def login
    user = User.where('username LIKE ? AND password LIKE ?', params[:username], params[:password])

    if user.length > 0
      render json: user.first
    else
      render nothing: true, status: :unauthorized
    end
  end

  def search
    user = User.find_by_username(params[:username])

    if user.nil?
      render nothing: true, status: :unauthorized
    else
      render json: user
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    puts @user.attributes

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:username, :password, :name, :device_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobs_helper.rb
module MobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobSyncBackend</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mobs/_form.html.erb
<%= form_for(@mob) do |f| %>
  <% if @mob.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mob.errors.count, "error") %> prohibited this mob from being saved:</h2>

      <ul>
      <% @mob.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_ids %><br>
    <%= f.text_field :user_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mobs/edit.html.erb
<h1>Editing mob</h1>

<%= render 'form' %>

<%= link_to 'Show', @mob %> |
<%= link_to 'Back', mobs_path %>

app/views/mobs/index.html.erb
<h1>Listing mobs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>User ids</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mobs.each do |mob| %>
      <tr>
        <td><%= mob.id %></td>
        <td><%= mob.user_ids %></td>
        <td><%= link_to 'Show', mob %></td>
        <td><%= link_to 'Edit', edit_mob_path(mob) %></td>
        <td><%= link_to 'Destroy', mob, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mob', new_mob_path %>

app/views/mobs/new.html.erb
<h1>New mob</h1>

<%= render 'form' %>

<%= link_to 'Back', mobs_path %>

app/views/mobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User ids:</strong>
  <%= @mob.user_ids %>
</p>

<%= link_to 'Edit', edit_mob_path(@mob) %> |
<%= link_to 'Back', mobs_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>MobSync Backend</h1>

<dl>
  <dt>Users</dt>
  <dd><a href="/users.json">/users.json</a></dd>

  <dt>Mobs</dt>
  <dd><a href="/mobs.json">/mobs.json</a></dd>
</dl>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Device:</strong>
  <%= @user.device_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>